### ISSUE TITLE
Package.getActivationCommands is deprecated.

### ISSUE THREAD

**Issue by gmr** [spiegela/atom-erlang-build#6]
Use `activationCommands` instead of `activationEvents` in your package.json
Commands should be grouped by selector as follows:

``` json
  "activationCommands": {
    "atom-workspace": ["foo:bar", "foo:baz"],
    "atom-text-editor": ["foo:quux"]
  }
```

```
Package.getActivationCommands (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:808:9)
Package.hasActivationCommands (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:733:20)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:187:24)
Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:179:12)
PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:372:14)
```

**Comment by jakrzus** [comment]
Am having this issue trying to run plugin 

`

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.11.6
**Thrown From**: [erlang-build](https://github.com/spiegela/atom-erlang-build) package 0.3.0


### Stack Trace

Failed to activate the erlang-build package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.activate (/packages/erlang-build/lib/erlang-build.coffee:15:24)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:230:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:875:27)
    at <anonymous>
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.33.4 
atom-clock 0.1.16 
atom-ember-author-kit 0.8.3 
atom-handlebars 1.3.0 
autocomplete-ruby 0.2.8 
comment 0.6.1 
dash 1.7.1 
editorconfig 2.2.2 
ember-snippets 3.0.2 
emberjs-atom 0.10.0 
erlang-build 0.3.0 
git-time-machine 2.1.0 
hbs-beautify 0.2.0 
heroku-tools 0.4.0 
language-erlang 3.2.0 
language-rspec 0.12.1 
platformio-ide-terminal 2.8.4 
rails-open-rspec 1.2.0 
rails-rspec 0.3.2 
rails-snippets 2.19.0 
rails-transporter 1.7.1 
ruby-block 0.3.6 
ruby-test 1.0.2 
split-diff 1.4.0 
tree-view-open-files 0.3.0 
v-bootstrap4 0.2.2 
```

`
Could it be related to this tread?
