### ISSUE TITLE
Failed to activate the erlang-build package

### ISSUE THREAD

**Issue by bluurn** [spiegela/atom-erlang-build#8]
Hi guys, I'm quite new to Erlang, yet I have found the entitled issue.

This issue appeared when I tried to build _mirror.erl_:

``` erlang
-module(mirror).
-export([mirror/1]).
mirror(Anything) -> Anything.
```

I am not sure whether this issue is caused by this code or the plugin, so would you be so kind to look into this issue.

Thank you! :+1: 

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [erlang-build](https://github.com/spiegela/atom-erlang-build) package, v0.3.0
### Stack Trace

Failed to activate the erlang-build package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/bluurn/.atom/packages/erlang-build/lib/erlang-build.coffee:15:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```
### Commands

```
     -0:27.1.0 core:close (atom-text-editor.editor.is-focused)
     -0:22.4.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
     -0:21 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:19.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:15.6.0 fuzzy-finder:toggle-buffer-finder (atom-text-editor.editor.is-focused)
     -0:14.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:14.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -0:14.2.0 tree-view:toggle (atom-text-editor.editor.is-focused)
  2x -0:12.3.0 fuzzy-finder:toggle-buffer-finder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:06.8.0 pane:reopen-closed-item (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:05.7.0 fuzzy-finder:toggle-file-finder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:04.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:04.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:03.9.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:01.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 erlang-build:compile (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "linter-haml",
      "execute-as-ruby",
      "placeholder-text",
      "todo-list",
      "todo-list",
      "placeholder-text"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-runner, v2.4.1
autocomplete-erlang, v1.1.1
autocomplete-ruby, v0.1.0
erlang-build, v0.3.0
language-erlang, v3.0.0
language-haml, v0.21.0
language-mongodb, v0.2.0
language-r, v0.2.0
language-sml, v0.3.0
linter, v1.1.0
linter-csslint, v0.0.14
linter-erlc, v0.3.0
linter-scss-lint, v1.0.5
project-manager, v1.15.10
ruby-block, v0.3.4
ruby-block-converter, v3.5.0
symbol-gen, v1.0.0
travis-ci-status, v0.15.1

# Dev
No dev packages
```

**Comment by bluurn** [comment]
Ok, I've found out that I have not installed rebar and configured the project properly, let's close this issue for now.

**Comment by epappas** [comment]
Same here, I am having erlang & rebar installed in my VM not in my laptop, where atom is.

**Comment by YussRoses** [comment]
someone found the correction for this error?

**Comment by plank-tools** [comment]
Still getting this error.
