### ISSUE TITLE
Failed to load the erlang-build package

### ISSUE THREAD

**Issue by rymir** [spiegela/atom-erlang-build#9]
[Enter steps to reproduce below:]
1. open the atom editor having the `erlang-build` package enabled

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [erlang-build](https://github.com/spiegela/atom-erlang-build) package, v0.3.0
### Stack Trace

Failed to load the erlang-build package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at inherits (/Users/tex/.atom/packages/erlang-build/node_modules/atom-message-panel/lib/utils.js:13:28)
    at Object.<anonymous> (/Users/tex/.atom/packages/erlang-build/node_modules/atom-message-panel/lib/MessagePanelView.js:18:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/tex/.atom/packages/erlang-build/node_modules/atom-message-panel/lib/index.js:2:21)
    at Module._compile (module.js:428:26)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ],
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "erlang-build": {}
}
```
### Installed Packages

``` coffee
# User
atom-ctags, v4.4.0
atom-python-debugger, v0.3.4
autocomplete-elixir, v1.4.2
autocomplete-erlang, v1.1.1
autocomplete-python, v0.10.1
erlang-build, v0.3.0
file-watcher, v0.4.0
language-elixir, v0.5.2
language-erlang, v3.0.0
language-hcl, v0.1.2
language-protobuf, v0.5.0
language-swift, v0.4.0
last-cursor-position, v0.9.0
minimap, v4.16.0
tabs-to-spaces, v0.11.1
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by spiegela** [comment]
Thanks for reporting this.  I'm certain this package is behind in the Atom plugin integration, as I haven't kept up with updates at all.  I really need to mark this repo as unmaintained, as I've switched back to Vim for Erlang development -- I may try out Atom again, but don't have the time right now.

**Comment by OvermindDL1** [comment]
Yeah I use VIM at home but work uses Atom (and Windows, bleh...) so...

[Enter steps to reproduce below:]
1. Launch atom

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [erlang-build](https://github.com/spiegela/atom-erlang-build) package, v0.3.0

### Stack Trace

Failed to activate the erlang-build package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (file:///C:/Users/<username>/.atom/packages/erlang-build/lib/erlang-build.coffee:15:23)
    at Package.module.exports.Package.activateNow (C:\Users\<username>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:183:20)
    at C:\Users\<username>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\<username>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\<username>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\<username>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\<username>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\<username>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (C:\Users\<username>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\<username>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\<username>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:497:46)
    at C:\Users\<username>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\atom-environment.js:754:28
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "autocomplete-go",
      "atom-powersnap",
      "activate-power-mode-delete",
      "autocomplete-dcd",
      "elm",
      "autocomplete-en-en",
      "spell-check",
      "latex-completions"
    ],
    "projectHome": "C:\\Users\\<username>\\Projects",
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
activate-power-mode, v0.7.0
ascii-codes, v0.3.3
ascii-hex, v0.2.0
atom-autocomplete-erlang, v0.6.19
atom-elixir, v0.2.1
atom-formatter-jsbeautify, v1.1.2
atom-svg-icon-snippets, v0.3.3
atomic-chrome, v0.3.0
autocomplete-asciidoc, v0.1.1
autocomplete-awk, v0.1.2
autocomplete-cmake, v0.3.1
autocomplete-elixir, v1.5.14
autocomplete-emojis, v2.5.0
autocomplete-erlang, v1.1.2
autocomplete-fortran, v0.9.0
autocomplete-gdscript, v0.4.0
autocomplete-glsl, v0.2.3
autocomplete-html-entities, v0.1.0
autocomplete-js-import, v1.0.1
autocomplete-json, v5.1.0
autocomplete-mathjax, v0.1.1
autocomplete-modules, v1.5.2
autocomplete-oracle, v0.4.0
autocomplete-php, v0.3.7
autocomplete-python, v1.8.2
autocomplete-xml, v0.8.3
build-elixir, v0.6.0
build-powershell, v0.3.4
character-table, v0.4.3
clipboard-plus, v0.5.1
data-atom, v0.21.0
elixir-cmd, v0.2.9
elm-format, v2.0.1
elm-snippets, v0.1.0
emmet, v2.4.3
emoji-code, v0.3.1
erlang-autocompile, v0.1.1
erlang-build, v0.3.0
es-identifier-highlight, v0.2.11
filesize, v0.4.2
fill-line, v1.0.0
fold-functions, v0.4.3
font-awesome-snippetset, v0.0.6
fonts, v1.6.0
git-checkout, v0.3.2
git-commit, v1.5.2
git-diff-details, v1.3.0
git-log, v0.4.1
go-config, v1.2.1
go-get, v1.0.3
hex, v0.6.2
highlight-bad-chars, v1.0.5
html-entitize, v1.1.0
language-javascript-jsx, v0.3.7
linter, v1.11.14
linter-checkbashisms, v0.1.5
linter-elixir-credo, v1.1.0
linter-elm-make, v0.12.2
linter-erlang, v0.3.1
linter-erlang-dialyzer, v0.0.1
minimap, v4.24.7
minimap-bookmarks, v0.3.1
minimap-codeglance, v0.4.5
minimap-cursorline, v0.2.0
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-pigments, v0.2.1
minimap-selection, v4.4.0
open-no-binaries, v0.1.1
phoenix-elixir-snippets, v0.4.0
pigments, v0.31.2
project-colorize, v0.2.0
qolor, v0.2.2
resize-indent, v0.3.0
svg-preview, v0.7.4
text-manipulation, v0.6.0
tree-view-git-branch, v0.1.2
tree-view-git-status, v1.0.2

# Dev
No dev packages
```
